<?php

namespace App\Modules\StockUnit\Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\StockUnit\Models\StockUnit;
use Illuminate\Support\Facades\DB;

class StockUnitSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('stock_units')->insert([
            ['name' => 'Centimeter', 'code' => 'CMS', 'unit_type' => 'simple', 'quantity_type' => 'length', 'description' => '0.01 meters', 'status' => 'active', 'icon' => 'FaRuler', 'unique_quantity_code_id' => 12, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Kilometer', 'code' => 'KME', 'unit_type' => 'simple', 'quantity_type' => 'length', 'description' => '1000 meters', 'status' => 'active', 'icon' => 'FaRuler', 'unique_quantity_code_id' => 22, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Meters', 'code' => 'MTR', 'unit_type' => 'simple', 'quantity_type' => 'length', 'description' => 'SI base unit of length', 'status' => 'active', 'icon' => 'FaRuler', 'unique_quantity_code_id' => 24, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Gross Yards', 'code' => 'GYD', 'unit_type' => 'simple', 'quantity_type' => 'length', 'description' => 'Measurement in yards', 'status' => 'active', 'icon' => 'FaRuler', 'unique_quantity_code_id' => 19, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Yards', 'code' => 'YDS', 'unit_type' => 'simple', 'quantity_type' => 'length', 'description' => 'Unit of length', 'status' => 'active', 'icon' => 'FaRuler', 'unique_quantity_code_id' => 43, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],

            // Area units
            ['name' => 'Square Feet', 'code' => 'SQF', 'unit_type' => 'simple', 'quantity_type' => 'area', 'description' => 'Derived unit of area', 'status' => 'active', 'icon' => 'FaShapes', 'unique_quantity_code_id' => 33, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Square Meters', 'code' => 'SQM', 'unit_type' => 'simple', 'quantity_type' => 'area', 'description' => 'Derived unit of area', 'status' => 'active', 'icon' => 'FaShapes', 'unique_quantity_code_id' => 34, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Square Yards', 'code' => 'SQY', 'unit_type' => 'simple', 'quantity_type' => 'area', 'description' => 'Derived unit of area', 'status' => 'active', 'icon' => 'FaShapes', 'unique_quantity_code_id' => 35, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],

            // Volume units
            ['name' => 'Cubic Meter', 'code' => 'CBM', 'unit_type' => 'simple', 'quantity_type' => 'volume', 'description' => 'Unit of volume', 'status' => 'active', 'icon' => 'FaCube', 'unique_quantity_code_id' => 10, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Cubic Centimeter', 'code' => 'CCM', 'unit_type' => 'simple', 'quantity_type' => 'volume', 'description' => '0.000001 cubic meters', 'status' => 'active', 'icon' => 'FaCube', 'unique_quantity_code_id' => 11, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Kiloliter', 'code' => 'KLR', 'unit_type' => 'simple', 'quantity_type' => 'volume', 'description' => '1000 liters', 'status' => 'active', 'icon' => 'FaTint', 'unique_quantity_code_id' => 21, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Milliliter', 'code' => 'MLT', 'unit_type' => 'simple', 'quantity_type' => 'volume', 'description' => '0.001 liters', 'status' => 'active', 'icon' => 'FaTint', 'unique_quantity_code_id' => 23, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'US Gallons', 'code' => 'UGS', 'unit_type' => 'simple', 'quantity_type' => 'volume', 'description' => 'Unit of volume', 'status' => 'active', 'icon' => 'FaTint', 'unique_quantity_code_id' => 41, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],

            // Weight units
            ['name' => 'Grams', 'code' => 'GMS', 'unit_type' => 'simple', 'quantity_type' => 'weight', 'description' => '0.001 kilograms', 'status' => 'active', 'icon' => 'FaWeight', 'unique_quantity_code_id' => 17, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Kilograms', 'code' => 'KGS', 'unit_type' => 'simple', 'quantity_type' => 'weight', 'description' => 'SI base unit of mass', 'status' => 'active', 'icon' => 'FaWeightHanging', 'unique_quantity_code_id' => 20, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Metric Tons', 'code' => 'MTS', 'unit_type' => 'simple', 'quantity_type' => 'weight', 'description' => '1000 kilograms', 'status' => 'active', 'icon' => 'FaWeightHanging', 'unique_quantity_code_id' => 25, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 3],
            ['name' => 'Quintal', 'code' => 'QTL', 'unit_type' => 'simple', 'quantity_type' => 'weight', 'description' => '100 kilograms', 'status' => 'active', 'icon' => 'FaWeight', 'unique_quantity_code_id' => 30, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Tonnes', 'code' => 'TON', 'unit_type' => 'simple', 'quantity_type' => 'weight', 'description' => '1000 kilograms', 'status' => 'active', 'icon' => 'FaWeightHanging', 'unique_quantity_code_id' => 39, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 3],

            // Measure units
            ['name' => 'Bags', 'code' => 'BAG', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => '50 KG bags', 'status' => 'active', 'icon' => 'FaBoxOpen', 'unique_quantity_code_id' => 1, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => 0.05, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2], // 1 bag = 0.05 MT
            ['name' => 'Bale', 'code' => 'BAL', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaBoxes', 'unique_quantity_code_id' => 2, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Bundles', 'code' => 'BDL', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaBoxes', 'unique_quantity_code_id' => 3, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Buckles', 'code' => 'BKL', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaLink', 'unique_quantity_code_id' => 4, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Billions of Units', 'code' => 'BOU', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaInfinity', 'unique_quantity_code_id' => 5, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Box', 'code' => 'BOX', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaBox', 'unique_quantity_code_id' => 6, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Bottles', 'code' => 'BTL', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaWineBottle', 'unique_quantity_code_id' => 7, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Bunches', 'code' => 'BUN', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaSeedling', 'unique_quantity_code_id' => 8, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Cans', 'code' => 'CAN', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaRecycle', 'unique_quantity_code_id' => 9, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Cartons', 'code' => 'CTN', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaBoxes', 'unique_quantity_code_id' => 13, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Dozen', 'code' => 'DOZ', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => '12 pieces', 'status' => 'active', 'icon' => 'FaBox', 'unique_quantity_code_id' => 14, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => 12.0, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Drum', 'code' => 'DRM', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaDrum', 'unique_quantity_code_id' => 15, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Great Gross', 'code' => 'GGR', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaCube', 'unique_quantity_code_id' => 16, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Gross', 'code' => 'GRS', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaCube', 'unique_quantity_code_id' => 18, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Numbers', 'code' => 'NOS', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaHashtag', 'unique_quantity_code_id' => 26, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Packs', 'code' => 'PAC', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaBoxes', 'unique_quantity_code_id' => 27, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Pieces', 'code' => 'PCS', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Individual pieces', 'status' => 'active', 'icon' => 'FaCube', 'unique_quantity_code_id' => 28, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Pairs', 'code' => 'PRS', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaLink', 'unique_quantity_code_id' => 29, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Rolls', 'code' => 'ROL', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaBoxes', 'unique_quantity_code_id' => 31, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Sets', 'code' => 'SET', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaThLarge', 'unique_quantity_code_id' => 32, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Tablets', 'code' => 'TBS', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaTabletAlt', 'unique_quantity_code_id' => 36, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Ten Gross', 'code' => 'TGM', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaBox', 'unique_quantity_code_id' => 37, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Thousands', 'code' => 'THD', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaHashtag', 'unique_quantity_code_id' => 38, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Tubes', 'code' => 'TUB', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaCircle', 'unique_quantity_code_id' => 40, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            ['name' => 'Units', 'code' => 'UNT', 'unit_type' => 'simple', 'quantity_type' => 'measure', 'description' => 'Unit of measure', 'status' => 'active', 'icon' => 'FaHashtag', 'unique_quantity_code_id' => 42, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],

            // Others
            ['name' => 'Others', 'code' => 'OTH', 'unit_type' => 'simple', 'quantity_type' => 'others', 'description' => 'Other units', 'status' => 'active', 'icon' => 'FaEllipsisH', 'unique_quantity_code_id' => 44, 'primary_stock_unit_id' => null, 'secondary_stock_unit_id' => null, 'conversion_factor' => null, 'created_at' => now(), 'updated_at' => now(), 'no_of_decimal_places' => 2],
            [
                'name' => 'Bags of 50 Kilograms',
                'code' => 'BAG of 50 KGS',
                'unit_type' => 'compound',
                'quantity_type' => 'measure',
                'description' => 'Bags of 50 Kilograms',
                'status' => 'active',
                'icon' => 'FaEllipsisH',
                'unique_quantity_code_id' => 44,
                'primary_stock_unit_id' => 19,
                'secondary_stock_unit_id' => 15,
                'conversion_factor' => 50.0,
                'created_at' => now(),
                'updated_at' => now(),
                'no_of_decimal_places' => 2
            ],
        ]);
    }
}
