<?php

namespace App\Modules\VoucherType\Database\Seeders;
use DB;
use Illuminate\Database\Seeder;
use App\Modules\VoucherType\Models\VoucherType;

class VoucherTypeSeeder extends Seeder
{
    public function run(): void
    {
        // VoucherType::create(['name' => 'Sample VoucherType']);
        $voucherTypes = [
            // Accounting Category (ID 1)
            [
                'id' => 1001,
                'parent_id' => null,
                'name' => 'Contra',
                'code' => 'CNTR',
                'voucher_category_id' => 1,
                'description' => 'For transfers between bank accounts or cash to bank',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaExchangeAlt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 1002,
                'parent_id' => null,
                'name' => 'Payment',
                'code' => 'PAYM',
                'voucher_category_id' => 1,
                'description' => 'For payments to suppliers or truck drivers',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaMoneyBill',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 1003,
                'parent_id' => null,
                'name' => 'Receipt',
                'code' => 'RCVP',
                'voucher_category_id' => 1,
                'description' => 'For receipts from distributors',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaMoneyCheck',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 1004,
                'parent_id' => null,
                'name' => 'Journal',
                'code' => 'JRNL',
                'voucher_category_id' => 1,
                'description' => 'For adjustments, accruals, and opening balances',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaBook',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 1005,
                'parent_id' => null,
                'name' => 'Purchase',
                'code' => 'PURC',
                'voucher_category_id' => 1,
                'description' => 'For goods received from suppliers like ACC',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaCartPlus',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 1006,
                'parent_id' => null,
                'name' => 'Sales',
                'code' => 'SALE',
                'voucher_category_id' => 1,
                'description' => 'For goods sold to distributors',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaCartArrowDown',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 1007,
                'parent_id' => null,
                'name' => 'Debit Note',
                'code' => 'DBNT',
                'voucher_category_id' => 1,
                'description' => 'For recording debit notes issued to distributors',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaArrowCircleDown',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 1008,
                'parent_id' => null,
                'name' => 'Credit Note',
                'code' => 'CRNT',
                'voucher_category_id' => 1,
                'description' => 'For recording credit notes received from suppliers',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaArrowCircleUp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 1009,
                'parent_id' => null,
                'name' => 'Reversing Journal',
                'code' => 'RVJL',
                'voucher_category_id' => 1,
                'description' => 'For reversing previous journal entries',
                'is_financial' => true,
                'is_hidden' => true,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaUndo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 1010,
                'parent_id' => null,
                'name' => 'Memo',
                'code' => 'MEMO',
                'voucher_category_id' => 1,
                'description' => 'For memorandum entries (non-posting)',
                'is_financial' => false,
                'is_hidden' => true,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaStickyNote',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Inventory Category (ID 2)

            [
                'id' => 2001,
                'parent_id' => null,
                'name' => 'Delivery Note',
                'code' => 'DLNT',
                'voucher_category_id' => 2,
                'description' => 'For goods dispatched to distributors',
                'is_financial' => false,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaTruck',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2002,
                'parent_id' => null,
                'name' => 'Receipt Note',
                'code' => 'RCNT',
                'voucher_category_id' => 2,
                'description' => 'For goods received without invoice',
                'is_financial' => false,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaReceipt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2003,
                'parent_id' => null,
                'name' => 'Rejection In',
                'code' => 'RJIN',
                'voucher_category_id' => 2,
                'description' => 'For rejected goods returned from distributors',
                'is_financial' => false,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaTimesCircle',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2004,
                'parent_id' => null,
                'name' => 'Rejection Out',
                'code' => 'RJOT',
                'voucher_category_id' => 2,
                'description' => 'For rejected goods returned to suppliers',
                'is_financial' => false,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaBan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2005,
                'parent_id' => null,
                'name' => 'Transfer Voucher',
                'code' => 'TRNS',
                'voucher_category_id' => 2,
                'description' => 'For internal godown transfers',
                'is_financial' => false,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaExchange',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2006,
                'parent_id' => null,
                'name' => 'Manufacturing Journal',
                'code' => 'MANJ',
                'voucher_category_id' => 2,
                'description' => 'For recording manufacturing processes',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaIndustry',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2007,
                'parent_id' => null,
                'name' => 'Physical Stock',
                'code' => 'PHSK',
                'voucher_category_id' => 2,
                'description' => 'For physical stock adjustments',
                'is_financial' => false,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaClipboardCheck',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Statutory Category (ID 3)
            [
                'id' => 3001,
                'parent_id' => null,
                'name' => 'Provident Fund Voucher',
                'code' => 'PFND',
                'voucher_category_id' => 3,
                'description' => 'For PF contributions',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaShieldAlt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3002,
                'parent_id' => null,
                'name' => 'ESI Payment Voucher',
                'code' => 'ESIP',
                'voucher_category_id' => 3,
                'description' => 'For Employee State Insurance payments',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaUserShield',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Payroll Category (ID 4)
            [
                'id' => 4001,
                'parent_id' => null,
                'name' => 'Salary Payment Voucher',
                'code' => 'SLRY',
                'voucher_category_id' => 4,
                'description' => 'For employee salary disbursements',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaMoneyBillWave',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4002,
                'parent_id' => null,
                'name' => 'Bonus Voucher',
                'code' => 'BONS',
                'voucher_category_id' => 4,
                'description' => 'For employee bonus payments',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaGift',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4003,
                'parent_id' => null,
                'name' => 'Attendance Voucher',
                'code' => 'ATND',
                'voucher_category_id' => 4,
                'description' => 'For recording employee attendance',
                'is_financial' => false,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaClock',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4004,
                'parent_id' => null,
                'name' => 'Payroll Voucher',
                'code' => 'PYRL',
                'voucher_category_id' => 4,
                'description' => 'For overall payroll processing',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaUsersCog',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Order Category (ID 5)
            [
                'id' => 5001,
                'parent_id' => null,
                'name' => 'Purchase Order',
                'code' => 'POVD',
                'voucher_category_id' => 5,
                'description' => 'For placing purchase orders with suppliers',
                'is_financial' => false,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaShoppingBag',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5002,
                'parent_id' => null,
                'name' => 'Sales Order',
                'code' => 'SOVD',
                'voucher_category_id' => 5,
                'description' => 'For receiving sales orders from distributors',
                'is_financial' => false,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaFileInvoice',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Assets Category (ID 6)
            [
                'id' => 6001,
                'parent_id' => null,
                'name' => 'Asset Acquisition Voucher',
                'code' => 'ACQT',
                'voucher_category_id' => 6,
                'description' => 'For purchasing fixed assets like trucks or machinery',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaPlusSquare',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6002,
                'parent_id' => null,
                'name' => 'Depreciation Voucher',
                'code' => 'DEPR',
                'voucher_category_id' => 6,
                'description' => 'For recording asset depreciation',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaChartLine',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6003,
                'parent_id' => null,
                'name' => 'Asset Disposal Voucher',
                'code' => 'DSPL',
                'voucher_category_id' => 6,
                'description' => 'For disposing of fixed assets',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaTrash',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Liabilities Category (ID 7)
            [
                'id' => 7001,
                'parent_id' => null,
                'name' => 'Loan Repayment Voucher',
                'code' => 'LNRP',
                'voucher_category_id' => 7,
                'description' => 'For repaying loans or mortgages',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaHandHoldingUsd',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7002,
                'parent_id' => null,
                'name' => 'Interest Payment Voucher',
                'code' => 'INTP',
                'voucher_category_id' => 7,
                'description' => 'For paying interest on loans',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaPercentage',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Expenses Category (ID 8)
            [
                'id' => 8001,
                'parent_id' => null,
                'name' => 'Rent Payment Voucher',
                'code' => 'RNTP',
                'voucher_category_id' => 8,
                'description' => 'For paying rent for warehouses or offices',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaHome',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8002,
                'parent_id' => null,
                'name' => 'Utility Bill Voucher',
                'code' => 'UTLB',
                'voucher_category_id' => 8,
                'description' => 'For paying utility bills (electricity, water)',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaBolt',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tax Category (ID 9)
            [
                'id' => 9001,
                'parent_id' => null,
                'name' => 'GST Input Voucher',
                'code' => 'GSTI',
                'voucher_category_id' => 9,
                'description' => 'For recording GST input tax credits',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaFileImport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9002,
                'parent_id' => null,
                'name' => 'GST Output Voucher',
                'code' => 'GSTO',
                'voucher_category_id' => 9,
                'description' => 'For recording GST output tax liabilities',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaFileExport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9003,
                'name' => 'TDS Payment Voucher',
                'code' => 'TDSP',
                'voucher_category_id' => 9,
                'description' => 'For TDS payments to government',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaHandHolding',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9004,
                'name' => 'TCS Payment Voucher',
                'code' => 'TCSP',
                'voucher_category_id' => 9,
                'description' => 'For TCS payments to government',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaCoins',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9005,
                'name' => 'Advance Tax Voucher',
                'code' => 'ADTX',
                'voucher_category_id' => 9,
                'description' => 'For advance tax payments',
                'is_financial' => true,
                'is_hidden' => false,
                'is_system' => false,
                'status' => 'active',
                'icon' => 'FaCalendarAlt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($voucherTypes as $type) {
            VoucherType::updateOrCreate(
                ['id' => $type['id']],
                $type
            );
        }


    }
}
